### ISSUE TITLE
DelimitedFiles.readdlm error - OS?

### ISSUE THREAD

**Issue by luschiro** [Iddingsite/DiffusionGarnet.jl#11]
I reckon this is just a silly OS error, but running tests with the DelimitedFiles.readdlm got me an error because of the way directories are in Windows. It might be a good idea to use `Filesystem` or something? New to Julia here.

```Julia
data = DelimitedFiles.readdlm("./Data/1D/Data_Grt_1D.txt", '\t', '\n', header=true)[1] # error
"test\Data\1D\Data_Grt_1D.txt" # my relative path that got the test going
```

**Comment by luschiro** [comment]
This occurs on the `runtests.jl` script, line 89

**Comment by Iddingsite** [comment]
Hey, thanks for testing it! 
It indeed seems to be a silly error on the path.
I cannot reproduce your error on a Windows though and the tests pass on the machine I just tried. 
Normally `/` is the universal character path so it works for both Mac, Linux and Windows.
Do you mind sharing the output of `versioninfo()`?

**Comment by Iddingsite** [comment]
Alright, I figured out it would be faster to just fix my code! 
Do you mind testing again the package with the new version 0.1.6 I just released and telling me if it works now?

**Comment by luschiro** [comment]
Will do later tonight, I'll let you know. Is this the best way to contact you? I can drop you an email, there are other things I would like to discuss, if that's ok.

**Comment by Iddingsite** [comment]
Great, fine by me!
Sure, my email is hugo.dominguez@unibe.ch, don't hesitate.
